#!/usr/bin/env python3
"""Refresh docs/stats.md from the working tree. Invoked by `make stats`.

Counts first-party sources only. Vendor trees (lib/hackrf, libusb, FFTW,
ATSC GNU Radio/libfec), Maven target/, and native build/obj dirs are excluded
so the numbers stay about *this* project, not imported dependencies.
"""
from __future__ import annotations

import datetime as dt
import os
import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "stats.md"
JAVA_MAIN = ROOT / "src/hackrf-sweep/src/main/java"
JAVA_TEST = ROOT / "src/hackrf-sweep/src/test/java"
SRC_C = ROOT / "src/hackrf-sweep/src-c"
DOCS = ROOT / "docs"
SCRIPTS = ROOT / "scripts"
ATSC_VENDOR_DIRS = (
    SRC_C / "atsc/lib",
    SRC_C / "atsc/fec",
    SRC_C / "atsc/shim",
)

SKIP_DIR_NAMES = {
    ".git",
    "target",
    "build",
    "obj",
    "node_modules",
    "lib",  # vendored hackrf / libusb / fftw
}

GENERATED_BANNER = (
    "<!-- Generated by scripts/repo-stats.py / `make stats`. Do not edit by hand. -->\n"
)


def run(args: list[str], cwd: Path | None = None) -> str:
    try:
        return subprocess.check_output(args, cwd=cwd or ROOT, text=True, stderr=subprocess.DEVNULL).strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return ""


def physical_lines(path: Path) -> tuple[int, int, int]:
    """Return (total, blank, nonempty) physical lines."""
    total = blank = 0
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return 0, 0, 0
    for line in text.splitlines():
        total += 1
        if not line.strip():
            blank += 1
    return total, blank, total - blank


def java_package(path: Path, root: Path) -> str:
    rel = path.relative_to(root).as_posix()
    parts = rel.split("/")
    if len(parts) == 1:
        return "(default)"
    return "/".join(parts[:-1])


def count_java_tree(root: Path) -> dict:
    by_pkg: dict[str, dict[str, int]] = defaultdict(lambda: {"files": 0, "lines": 0})
    files = 0
    lines = 0
    if not root.is_dir():
        return {"files": 0, "lines": 0, "packages": {}}
    for path in sorted(root.rglob("*.java")):
        n, _, _ = physical_lines(path)
        pkg = java_package(path, root)
        by_pkg[pkg]["files"] += 1
        by_pkg[pkg]["lines"] += n
        files += 1
        lines += n
    return {"files": files, "lines": lines, "packages": dict(by_pkg)}


def count_dir(root: Path, globs: list[str], skip_roots: tuple[Path, ...] = ()) -> tuple[int, int]:
    files = lines = 0
    if not root.exists():
        return 0, 0
    seen: set[Path] = set()
    for g in globs:
        for path in root.rglob(g):
            if not path.is_file() or path in seen:
                continue
            if any(p in SKIP_DIR_NAMES for p in path.parts):
                continue
            if any(path.is_relative_to(skip) for skip in skip_roots):
                continue
            seen.add(path)
            n, _, _ = physical_lines(path)
            files += 1
            lines += n
    return files, lines


def test_inventory() -> dict:
    unit_classes = 0
    hw_classes = 0
    support = 0
    test_methods = 0
    hw_methods = 0
    if not JAVA_TEST.is_dir():
        return {}
    for path in JAVA_TEST.rglob("*.java"):
        text = path.read_text(encoding="utf-8", errors="replace")
        methods = len(re.findall(r"@Test\b", text))
        hw = len(re.findall(r"@HardwareTest\b", text))
        test_methods += methods
        hw_methods += hw
        name = path.name
        if re.search(r"@interface\s+\w+", text):
            support += 1
        elif name.endswith("IT.java"):
            hw_classes += 1
        elif methods > 0:
            unit_classes += 1
        else:
            support += 1
    return {
        "unit_classes": unit_classes,
        "hw_classes": hw_classes,
        "support": support,
        "test_methods": test_methods,
        "hw_methods": hw_methods,
    }


def mermaid_inventory() -> list[tuple[str, str]]:
    found = []
    md_files = list(DOCS.rglob("*.md")) + [
        ROOT / "README.md",
        ROOT / "AGENTS.md",
        ROOT / "CONTRIBUTING.md",
        ROOT / "CHANGELOG.md",
    ]
    fence = re.compile(r"^```mermaid\n(.*?)```", re.M | re.S)
    for path in md_files:
        if not path.is_file() or path.name == "stats.md":
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        for i, block in enumerate(fence.findall(text), 1):
            kind = block.strip().splitlines()[0].split()[0] if block.strip() else "?"
            rel = path.relative_to(ROOT).as_posix()
            found.append((rel, kind))
    found.sort()
    return found


def makefile_targets(path: Path) -> list[str]:
    if not path.is_file():
        return []
    names = []
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        m = re.match(r"^([A-Za-z][A-Za-z0-9_.-]*):", line)
        if m and m.group(1) not in names:
            names.append(m.group(1))
    return names


def parse_pin(text: str, pattern: str) -> str:
    m = re.search(pattern, text)
    return m.group(1) if m else "?"


def metadata() -> dict:
    pom = (ROOT / "src/hackrf-sweep/pom.xml").read_text(encoding="utf-8", errors="replace")
    mk = (ROOT / "src/hackrf-sweep/Makefile").read_text(encoding="utf-8", errors="replace")
    ver = (ROOT / "src/hackrf-sweep/src/main/java/jspectrumanalyzer/Version.java").read_text(
        encoding="utf-8", errors="replace"
    )
    query = (
        ROOT / "src/hackrf-sweep/src/main/java/jspectrumanalyzer/nativebridge/HackRFDeviceQuery.java"
    ).read_text(encoding="utf-8", errors="replace")
    presets = (
        ROOT / "src/hackrf-sweep/src/main/java/jspectrumanalyzer/ui/QuickSelectPreset.java"
    ).read_text(encoding="utf-8", errors="replace")
    freq_usa = ROOT / "src/hackrf-sweep/src/main/resources/freq-usa.csv"
    alloc_rows = 0
    if freq_usa.is_file():
        alloc_rows = max(0, sum(1 for _ in freq_usa.open(encoding="utf-8", errors="replace")) - 1)
    preset_n = len(re.findall(r'^\s+[A-Z0-9_]+\("', presets, flags=re.M))
    return {
        "app_version": parse_pin(ver, r'version\s*=\s*"([^"]+)"'),
        "homepage": parse_pin(ver, r'url\s*=\s*"([^"]+)"'),
        "java_release": parse_pin(pom, r"<release>(\d+)</release>"),
        "sdk_pin": parse_pin(mk, r"HACKRF_SDK_PIN=\s*(\S+)"),
        "min_firmware": parse_pin(query, r'MIN_FIRMWARE\s*=\s*"([^"]+)"'),
        "presets": preset_n,
        "alloc_rows": alloc_rows,
    }


def largest_java(limit: int = 8) -> list[tuple[str, int]]:
    rows = []
    for root in (JAVA_MAIN, JAVA_TEST):
        if not root.is_dir():
            continue
        for path in root.rglob("*.java"):
            n, _, _ = physical_lines(path)
            rows.append((path.relative_to(ROOT).as_posix(), n))
    rows.sort(key=lambda r: r[1], reverse=True)
    return rows[:limit]


def git_info() -> dict:
    return {
        "commit": run(["git", "rev-parse", "--short", "HEAD"]) or "unknown",
        "branch": run(["git", "rev-parse", "--abbrev-ref", "HEAD"]) or "unknown",
        "date": run(["git", "log", "-1", "--format=%ci"]) or "unknown",
        "commits": run(["git", "rev-list", "--count", "HEAD"]) or "?",
        "authors": run(["git", "shortlog", "-sn", "HEAD"]),
    }


def pie_slice(label: str, value: int) -> str:
    safe = label.replace('"', "'")
    return f'    "{safe}" : {value}'


def render(md: dict) -> str:
    now = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    main = md["main"]
    test = md["test"]
    tests = md["tests"]
    git = md["git"]
    meta = md["meta"]
    mermaid = md["mermaid"]
    docs_files, docs_lines = md["docs"]
    scripts_files, scripts_lines = md["scripts"]
    c_files, c_lines = md["c"]
    root_targets = md["root_targets"]
    sub_targets = md["sub_targets"]

    first_party = main["lines"] + test["lines"] + docs_lines + scripts_lines + c_lines

    def pkg_table(tree: dict) -> str:
        rows = sorted(tree["packages"].items(), key=lambda kv: (-kv[1]["lines"], kv[0]))
        lines = ["| Package | Files | Lines |", "|---|---:|---:|"]
        for name, rec in rows:
            lines.append(f"| `{name}` | {rec['files']} | {rec['lines']} |")
        return "\n".join(lines)

    author_rows = []
    for line in git["authors"].splitlines()[:12]:
        line = line.strip()
        if not line:
            continue
        parts = line.split("\t", 1)
        if len(parts) == 2:
            author_rows.append(f"| {parts[1]} | {parts[0].strip()} |")
    authors_md = "| Author | Commits |\n|---|---:|\n" + "\n".join(author_rows) if author_rows else "_git unavailable_"

    mermaid_rows = ["| File | Type |", "|---|---|"]
    kinds: dict[str, int] = defaultdict(int)
    for rel, kind in mermaid:
        mermaid_rows.append(f"| `{rel}` | `{kind}` |")
        kinds[kind] += 1

    largest = ["| File | Lines |", "|---|---:|"]
    for rel, n in md["largest"]:
        largest.append(f"| `{rel}` | {n} |")

    pie = "\n".join(
        [
            "```mermaid",
            "pie showData",
            "    title First-party physical lines",
            pie_slice("Java main", main["lines"]),
            pie_slice("Java test", test["lines"]),
            pie_slice("Docs", docs_lines),
            pie_slice("Scripts + first-party C/C++", scripts_lines + c_lines),
            "```",
        ]
    )

    kinds_pie_lines = ["```mermaid", "pie showData", "    title Mermaid diagrams by type"]
    for k, n in sorted(kinds.items(), key=lambda kv: (-kv[1], kv[0])):
        kinds_pie_lines.append(pie_slice(k, n))
    kinds_pie_lines.append("```")

    return f"""{GENERATED_BANNER}
# Repository stats

Refreshed **{now}** from `{git['commit']}` on `{git['branch']}` (last commit {git['date']}).

Regenerate:

```bash
make stats
# or
python3 scripts/repo-stats.py
```

Vendor trees (`src/hackrf-sweep/lib/hackrf`, libusb, FFTW, and `src-c/atsc/{{lib,fec,shim}}` GNU Radio/libfec), `target/`, and `build/` are **excluded**. These numbers describe first-party code and docs.

## Snapshot

| | |
|---|---|
| App version | `{meta['app_version']}` |
| Java `--release` | {meta['java_release']} |
| Host SDK pin | `{meta['sdk_pin']}` |
| Minimum firmware | `{meta['min_firmware']}` |
| Quick Select presets | {meta['presets']} |
| USA allocation rows | {meta['alloc_rows']} |
| Git commits on this branch | {git['commits']} |
| First-party lines (all counted trees) | {first_party} |

{pie}

## Java by area

Production (`src/main/java`): **{main['files']}** files, **{main['lines']}** lines.

{pkg_table(main)}

Tests (`src/test/java`): **{test['files']}** files, **{test['lines']}** lines.

{pkg_table(test)}

### Tests

| Kind | Count |
|---|---:|
| Unit test classes (`@Test`, not `*IT`) | {tests['unit_classes']} |
| `@Test` methods (unit + hardware IT) | {tests['test_methods']} |
| Hardware IT classes (`*IT`) | {tests['hw_classes']} |
| `@HardwareTest` methods | {tests['hw_methods']} |
| Support types (fakes, annotations, helpers) | {tests['support']} |

`make test` runs the unit classes only. `make test-hw` runs the hardware IT and skips if no radio is enumerated.

## Other first-party trees

| Tree | Files | Lines |
|---|---:|---:|
| Docs (`docs/`) | {docs_files} | {docs_lines} |
| Scripts (`scripts/`) | {scripts_files} | {scripts_lines} |
| First-party C/C++ / patch (`src-c/`) | {c_files} | {c_lines} |

## Build surface

| Makefile | Documented / named targets |
|---|---|
| Root | {len(root_targets)} ({', '.join('`'+t+'`' for t in root_targets)}) |
| `src/hackrf-sweep` | {len(sub_targets)} |

## Diagrams

{len(mermaid)} Mermaid fences in first-party Markdown. Check they still parse with `make mermaid`.

{chr(10).join(mermaid_rows)}

{chr(10).join(kinds_pie_lines)}

## Largest first-party Java files

{chr(10).join(largest)}

`HackRFSweepSpectrumAnalyzer.java` is the Swing shell. Prefer growing `core/` and tests rather than this class.

## Git authors

{authors_md}

## How this is counted

- Physical lines (newline-separated), UTF-8, replacement on decode errors.
- A Java *unit test class* is a file that contains `@Test` and is not named `*IT.java`.
- Quick Select presets are enum constants in `QuickSelectPreset`.
- USA allocation rows are data lines in `freq-usa.csv` (header excluded).
- Re-run after large moves or new packages so [AGENTS.md](../AGENTS.md) can point here instead of baking stale counts.
"""


def main() -> int:
    os.chdir(ROOT)
    md = {
        "main": count_java_tree(JAVA_MAIN),
        "test": count_java_tree(JAVA_TEST),
        "tests": test_inventory(),
        "docs": count_dir(DOCS, ["*.md"]),
        "scripts": count_dir(SCRIPTS, ["*.sh", "*.py", "*.rules"]),
        "c": count_dir(SRC_C, ["*.c", "*.cc", "*.cpp", "*.h", "*.patch"], ATSC_VENDOR_DIRS),
        "mermaid": mermaid_inventory(),
        "root_targets": makefile_targets(ROOT / "Makefile"),
        "sub_targets": makefile_targets(ROOT / "src/hackrf-sweep/Makefile"),
        "largest": largest_java(),
        "git": git_info(),
        "meta": metadata(),
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(md), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    print(
        f"  java main {md['main']['files']} files / {md['main']['lines']} lines; "
        f"tests {md['tests']['unit_classes']} classes, {md['tests']['test_methods']} @Test"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
